version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: amazon.db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: mark
      POSTGRES_PASSWORD: tebi123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
